version: "3.7"
services:
    web:
        image: nginx:latest
        restart: always
        depends_on:
            - adminer
        volumes:
            - ./deploy/cert/${DOCKER_ENV}:/etc/nginx/cert:ro
            - ./deploy/nginx/templates:/etc/nginx/templates
            - ./deploy/nginx/logs:/web/logs/nginx
            - adminer_data:/var/www/html:ro
            - .:/opt/www
        ports:
            - 80:${DOCKER_WEB_PORT}
            - 443:443
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
    server:
        build:
            context: ./deploy/docker/server
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_server_hyperf
        image: wikiforest/hyperf:${DOCKER_SERVER_IMAGE_TAB}
        restart: always
        tty: true
        volumes:
            - ./server:/opt/www
    ui:
        build:
            context: ./deploy/docker/ui
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_ui_nextjs
        image: wikiforest/nextjs:${DOCKER_UI_IMAGE_TAB}
        restart: always
        tty: true
        volumes:
            - ./ui:/opt/www
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        expose:
            - ${DOCKER_DB_PORT}
    adminer:
        build: ./deploy/docker/adminer
        restart: always
        volumes:
            - adminer_data:/var/www/html
        environment:
            ADMINER_PLUGINS: "tables-filter edit-foreign"
            ADMINER_DESIGN: "ng9"
    portainer:
        image: portainer/portainer:alpine
        container_name: portainer
        command: -H unix:///var/run/docker.sock -p :9001
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

volumes:
    mysql_data:
    adminer_data:
    portainer_data:
