version: "3.8"
services:
    web:
        image: nginx:latest
        restart: always
        networks:
            - default
            - logger_net
        depends_on:
            - adminer
            - fluentd
        volumes:
            - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./deploy/cert/${DOCKER_ENV}:/etc/nginx/cert:ro
            - ./deploy/nginx/templates:/etc/nginx/templates
            - adminer_data:/var/www/html:ro
        ports:
            - 80:${DOCKER_WEB_PORT}
            - 443:443
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
    server:
        build:
            context: ./server
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_server_hyperf
        image: wikiforest/hyperf:${DOCKER_SERVER_IMAGE_TAB}
        restart: always
        tty: true
        networks:
            - default
            - logger_net
        depends_on:
            - fluentd
        deploy:
            update_config:
                order: start-first
        volumes:
            - ./server:/opt/www
            - server_vendor:/opt/www/vendor
            - server_runtime:/opt/www/runtime
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24225
                tag: server.stdout
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_ui_nextjs
        image: wikiforest/nextjs:${DOCKER_UI_IMAGE_TAB}-${DOCKER_ENV}
        restart: always
        tty: true
        volumes:
            - ./ui:/opt/www
            - ui_node_modules:/opt/www/node_modules
            - ui_next:/opt/www/.next
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./deploy/mysql/conf.d:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        expose:
            - ${DOCKER_DB_PORT}
    adminer:
        build: ./deploy/docker/adminer
        image: wikiforest/adminer-${DOCKER_ENV}
        restart: always
        volumes:
            - adminer_data:/var/www/html
        environment:
            ADMINER_PLUGINS: "tables-filter edit-foreign"
            ADMINER_DESIGN: "ng9"
    fluentd:
        build: ./deploy/docker/fluentd
        image: wikiforest/fluentd-${DOCKER_ENV}
        networks:
            - default
            - logger_net
        volumes:
            - ./deploy/fluentd/conf:/fluentd/etc
            - ./deploy/fluentd/logs:/data
        ports:
            - "24224:24224"
            - "24224:24224/udp"
            - "24225:24225"
            - "24225:24225/udp"
    # portainer:
    #     image: portainer/portainer:alpine
    #     container_name: portainer
    #     command: -H unix:///var/run/docker.sock -p :9001
    #     restart: always
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - portainer_data:/data

networks:
    logger_net:

volumes:
    mysql_data:
    adminer_data:
    server_vendor:
    server_runtime:
    ui_node_modules:
    ui_next:
