version: "3.7"
services:
    web:
        image: nginx:latest
        restart: always
        depends_on:
            - adminer
        volumes:
            - ./deploy/nginx/templates:/etc/nginx/templates
            - ./deploy/nginx/logs:/web/logs/nginx
            - adminer_data:/var/www/html:ro
            - .:/opt/www
        ports:
            - 80:${DOCKER_WEB_PORT}
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
    server:
        build:
            context: ./deploy/docker/server
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_server_hyperf
        image: wikiforest/hyperf:${DOCKER_SERVER_IMAGE_TAB}
        entrypoint: ["php", "/opt/www/server/bin/hyperf.php", "start"]
        restart: always
        expose:
            - 9501
            - 9502
        tty: true
        volumes:
            - .:/opt/www
    ui:
        build:
            context: ./deploy/docker/ui
            dockerfile: Dockerfile.${DOCKER_ENV}
        container_name: wiki_ui_nextjs
        image: wikiforest/nextjs:${DOCKER_UI_IMAGE_TAB}
        restart: always
        tty: true
        expose:
            - 3000
        volumes:
            - .:/opt/www
    db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        expose:
            - ${DOCKER_DB_PORT}
    adminer:
        build: ./deploy/docker/adminer
        restart: always
        volumes:
            - adminer_data:/var/www/html
            - ./deploy/adminer/pepa-linha-dark:/var/www/html/designs/pepa-linha-dark
        environment:
            ADMINER_PLUGINS: "tables-filter edit-foreign"
            ADMINER_DESIGN: "ng9"
        expose:
            - 9000
    portainer:
        image: portainer/portainer:alpine
        container_name: portainer
        command: -H unix:///var/run/docker.sock -p :9001
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        expose:
            - 9001
            - 8000

volumes:
    mysql_data:
    adminer_data:
    portainer_data:
