version: "3.8"
services:
    nginx:
        build:
            context: ./nginx
            args:
                DOCKER_ENV: ${DOCKER_ENV}
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
        image: wikiforest/nginx:latest
        restart: always
        ports:
            - 80:${DOCKER_WEB_PORT}
            - 443:443
        networks:
            - default
            - logger_net
        depends_on:
            - fluentd
        volumes:
            - adminer_data:/var/www/html:ro
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
            args:
                DOCKER_ENV: ${DOCKER_ENV}
                COMPOSER_ARGS: ${DOCKER_COMPOSER_ARGS}
        container_name: wiki_server_hyperf
        image: wikiforest/hyperf:${DOCKER_SERVER_IMAGE_TAB}
        restart: always
        tty: true
        networks:
            - default
            - logger_net
        depends_on:
            - fluentd
        deploy:
            update_config:
                order: start-first
        volumes:
            - ./server:/opt/www
            - server_vendor:/opt/www/vendor
            - server_runtime:/opt/www/runtime
        logging:
            driver: "fluentd"
            options:
                fluentd-address: localhost:24225
                tag: server.stdout
    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        container_name: wiki_ui_nextjs
        image: wikiforest/nextjs:${DOCKER_UI_IMAGE_TAB}-${DOCKER_ENV}
        restart: always
        tty: true
        entrypoint: ["yarn", "dev"]
        volumes:
            - ./ui:/opt/www
            - ui_node_modules:/opt/www/node_modules
            - ui_next:/opt/www/.next
    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mysql_data:/var/lib/mysql
            - ./deploy/mysql/conf.d:/etc/mysql/conf.d
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DOCKER_DB_PASSWD}
        ports:
            - ${DOCKER_DB_PORT}:${DOCKER_DB_PORT}
    fluentd:
        build: ./deploy/docker/fluentd
        image: wikiforest/fluentd-${DOCKER_ENV}
        networks:
            - default
            - logger_net
        volumes:
            - ./deploy/fluentd/conf:/fluentd/etc
            - ./deploy/fluentd/logs:/data
        ports:
            - "24224:24224"
            - "24224:24224/udp"
            - "24225:24225"
            - "24225:24225/udp"
    adminer:
        build: ./deploy/docker/adminer
        image: wikiforest/adminer-${DOCKER_ENV}
        restart: always
        volumes:
            - adminer_data:/var/www/html
        environment:
            ADMINER_PLUGINS: "tables-filter edit-foreign"
            ADMINER_DESIGN: "ng9"

networks:
    logger_net:

volumes:
    mysql_data:
    adminer_data:
    server_vendor:
    server_runtime:
    ui_node_modules:
    ui_next:
