FROM node:14-alpine3.10

COPY ./ui /opt/www/ui

WORKDIR /opt/www/ui

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && yarn \
    && yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]
